### ISSUE TITLE
Reporter dot is too big and gets in the way of main site features like login

### ISSUE THREAD

**Issue by samhatoum** [meteor-velocity/html-reporter#54]
Typically the login to a site is in the top right corner. The HTML reporter is far too big and immovable that it's impractical to use in real-world cases.

We should restore it back to a smaller dot without a corner and make this dot user-movable with memory. 

Thoughts / alternatives / objections?

**Comment by awatson1978** [comment]
This is pretty obvious.  I mentioned it months ago, and was brushed aside.  Glad that somebody else is finally recognizing this usability issue.  Unfortunately, the small dot is problematic also; so simply resizing doesn't solve the issue.  

Two suggestions:
1) a configuration object that lets a developer specify which corner to display the dot in, similar to the github-ribbons.
https://github.com/blog/273-github-ribbons

2) a sidebar that can be toggled with keyboard shortcuts from mousetrap or keymaster.
http://semantic-ui.com/modules/sidebar.html#/definition
https://atmospherejs.com/keymaster/keymaster

The latter is a fairly big redesign, and begs the question of whether it should be included in this particular repository, or made into something along the lines of ``html-reporter-panel``.

**Comment by rdickert** [comment]
Taking away the background from the dot is also problematic as contrast with the underlying page can be a problem - I don't think I'd recommend that. User-changeable location would be great, though. When this came up before, @Sanjo also suggested a configurable keyboard shortcut which might toggle the overlay and/or toggle the visibility of the dot. One other random idea: a skinny bar that would 'fly out' when you mouse over it. Yet another possibility: a header reserved for the reporter that actually displaces the app content down (Could we reliably do that?). This would never step on app content at all at the cost of being more visually intrusive (but you could scroll slightly to see the true look of the app).

**Comment by Batistleman** [comment]
:+1: for me the bottom left corner would do the trick :-)

**Comment by samhatoum** [comment]
What about another browser tab all together, and we can get the favico to change color and animate.

tab-reporter :)

**Comment by awatson1978** [comment]
They're all great ideas.  Let's not box ourselves into thinking this is an either-or decision, or that we need a one-size fits all approach.  Having a half dozen reporters to choose from could be a very appreciated feature.  Let's fork the html-reporter and let people experiment a bit with favicons, panels, keyboard shortcuts, overlays, routes, corners, etc.  

html-reporter
html-reporter-corners
html-reporter-slidepanel
html-reporter-favicon
html-reporter-hotkey
html-reporter-statuspage

**Comment by rdickert** [comment]
Just saw this article about cross-tab communication using localstorage. Apparently, it fires events you can listen to. This might allow a reporter that runs in a different tab but could show a dismissable alert in the main app.

http://ponyfoo.com/articles/cross-tab-communication

**Comment by queso** [comment]
Awesome article! Would have never thought of doing it that way.


--Josh Owens | 513-678-7081 | http://joshowens.me | @joshowens

**Comment by rjsmith** [comment]
I am hitting the same problem when trying to automate my Meteor UI using meteor-robotframework.  The webdriver (PhantomJs or Chrome) cannot click on the accounts-ui link in the app's header bar because it is covered by the html reporter.  I have moved the position of the accounts-ui link as a workround, but that just doesn't look very good!

As well as some of the other suggestions above, would it be possible to automatically hide / disable the html reporter if the browser session is running on a mirror url ? (e..g http://localhost:5000).  I don't see any need to have the html reporter visible on a mirrored session, which is only going to be used by an automated test anyhow (apart maybe from the html reporter automated tests themselves!).

**Comment by samhatoum** [comment]
Would you be able to do a PR? Should be an easy fix for the reporter.  The [same guard as cucumber](https://github.com/xolvio/meteor-cucumber/blob/master/server.js#L9) will do it at the top of the reporter files.

On the client side, you can use the [isMirror Meteor method](https://github.com/meteor-velocity/velocity/blob/develop/mirrors/Mirror.js#L160)

**Comment by samhatoum** [comment]
The fix above will at least let webdriver/robot do their thing. This issue is still open

**Comment by rjsmith** [comment]
Sure, will try. Which branch should I make my changes on?

**Comment by Sanjo** [comment]
@rjsmith Base your pull-request on the devel branch ;-)

**Comment by rjsmith** [comment]
OK, will do.

What should the scope of the returned value from the velocity/isMirror method call be (I'm following [this pattern](https://www.discovermeteor.com/patterns/5828387))?  

If I use a Session variable, then this state leaks out of Velocity HTML Reporter and into the rest of the application.  If this is OK (and indeed, could be seen as a useful benefit?), what should the Session variable be called?  How about 'velocity.isMirror' ?

If not, then I wlll use a ReactiveVar on the 'velocity' template instance object instead.

**Comment by samhatoum** [comment]
A reasonably named var like `velocity-html-reporter` should do the trick

And thanks!

**Comment by rjsmith** [comment]
Ok, almost ready to commit.  I have written the logic so that, by default, the status widget is NOT shown when the 'velocity' template is first rendered.  It will only be shown when the call to 'velocity/isMirror' returns with a (false) value. This ensures that if the browser *is* running in a mirror, the widget will never be added to the DOM. This eliminates any race conditions between automated tests running, and the widget disappearing.  Sounds OK?

**Comment by samhatoum** [comment]
perfect, it should only a few milliseconds

**Comment by loneleeandroo** [comment]
I just make it smaller if there are no failed tests. You can still click it to get the overlay as well.

```
#velocity-status-widget.pass {
  width: 30px;
  background-color: #21954f;
}
```

**Comment by mbabauer** [comment]
I am running into this problem now as well, and wanted to know if there were any long-term solutions.  My issue is that the overlay works fine when I am using the program in a browser with the window set large, but I am not trying to test my site as an Android/Cordova app, and the overlay literally sits right where the navigation bar shrinks to, basically making it impossible to hit the drop-down button to sign-in.  I haven't tried @loneleeandroo 's solution above, but for now I am just running my app with `--production` to simply turn off testing, but this also breaks hot code deploy too, and it takes FOREVER to get the Android device running because it has to do a full build every time.

Anyway, sorry for the long post.  Can't wait to see what you guys come up with.

**Comment by Sanjo** [comment]
Customizing the html-reporter dot is not a big problem. Just use the Developer Tools in your browser to find out the selectors, and the overwrite the CSS and put !important behind each CSS rule.

Here is an example how to move the dot to the bottom right corner:

```css
#velocity-status-widget {
  top: auto !important;
  bottom: -150px !important;
  -webkit-transform: translate(50%, -50%) rotate(45deg) !important;
  -webkit-transform-origin: 50% 50% !important;
  -o-transform: translate(50%, -50%) rotate(45deg) !important;
  -o-transform-origin: 50% 50% !important;
  transform: translate(50%, -50%) rotate(45deg) !important;
}
```

Just put this into one of your stylesheets of your app.

@mbabauer For mobile you can use a CSS media query.

**Comment by mbabauer** [comment]
@Sanjo This coupled with @loneleeandroo 's CSS worked perfectly in my case.  Thanks!
