### ISSUE TITLE
Doesn't work in latest Chrome Browser

### ISSUE THREAD

**Issue by Anonyfox** [meteor-velocity/html-reporter#64]
The triangle shows up, the dot flips from red to green if tests pass, and so on. But a click on the triangle does just nothing. No errors, no warnings, no reaction. 

Same app/site works perfectly in firefox and safari. *It even works within the latest Internet Explorer on my windows10 preview inside of parallels on my iMac with OSX yosemite.* But not in Chrome, version 41. 

I have no clue why.

**Comment by samhatoum** [comment]
have you checked the DOM to see if there's anything on top of it?

**Comment by rissem** [comment]
I'm having trouble reproducing this issue (mostly because it's windows10 preview and that's not available on BrowserStack). I do not see this issue on Chrome 41 for Mac or Chrome 41 for Windows 8.1. Are you seeing anything  suspicious in the console? If you could determine if the click event is registering that would be helpful (https://github.com/meteor-velocity/html-reporter/blob/devel/lib/client-report.js#L253)

**Comment by samhatoum** [comment]
I've not been able to replicate. Still an issue @Anonyfox ?
